version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g @angular/cli
      - npm install
  build:
    commands:
      - ng build --prod
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - '**/*'
